#########################################################################
# NMEA200_ROS2_GW EngineControl.srv
# Copyright TurkuAMK 2025
# Contact: jaakko.il.saarela@turkuamk.fi
# NOTE: This Server message is used in NMEA200_ROS2_GW to control remote status.
#       operational_action = 0 -> request current status
#       operational_action = 1 -> set new status
#       
#       if operational_action is 1 then new_state will be set as new operational_state.
#       if remote_arcion is 0 then response.current_operational_state will describe curret value.
#       response.current_operational_state = 0-> vessel is in local control only.
#       response.current_operational_state = 1 -> vessel is in remote controlled only.
#       response.current_operational_state = 2 -> vessel is in autonomous local conrtolled only.
#       response.current_operational_state = 3 -> vessel is in aautonomous AND remote controlled.       
#
#********** Specific Error Codes **************************************
#       if action fails then response.status will be set false and error_code desribes the error
#       response.error_code =  0 -> success
#       response.error_code = -1 -> Remote control cannot set online
#       response.error_code = -2 -> No response or mismatched response from DCU Motor
#       response.error_code = -3 -> No response or mismatched response from DCU rudder
# 

Nmea2kCommonMsgHeaderStruct header
uint8   operational_action
uint8   new_state
---
bool    status
uint8   current_operational_state  
int8    error_code